name_model = "10B"
project = "johannes_debug"

[train]
micro_bs = 2
sharding_strategy = "SHARD_GRAD_OP"
ac_ckpt = true
# torch_compile = false
[train.memory_profiler]
freq = 100
snapshot_dir = "./snapshots"

[optim]
batch_size = 128 #2M tokens bs
warmup_steps = 1000
total_steps = 88_000
lr = 3e-4

[data]
seq_length = 2048
fake = true

# [ckpt]
# interval = 10
# path = "./ckpt"