name: rl
enable_pane_titles: true

windows:
  - RL:
      layout: even-vertical
      panes:
        - Trainer:
        - Orchestrator:
          - |
            while true; do
              echo "Waiting for orchestrator log file..."
              while [ ! -f logs/orchestrator.loguru ]; do sleep 1; done
              echo "Following orchestrator.loguru..."
              tail -F logs/orchestrator.loguru
            done
        - Inference:
          - |
            while true; do
              echo "Waiting for inference log file..."
              while [ ! -f logs/inference.log ]; do sleep 1; done
              echo "Following inference.log..."
              tail -F logs/inference.log
            done
  - Monitor:
      layout: even-horizontal
      panes:
        - GPU: nvtop
        - CPU: htop
            